# Generated by Django 3.0.8 on 2020-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_yandexnewsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
