# Generated by Django 3.0.8 on 2020-07-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_triggerphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('vk_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('members_count', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('site', models.CharField(max_length=200)),
                ('photo_100', models.URLField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VKSource',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('vk_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VKPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('text', models.CharField(max_length=3000)),
                ('comments', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('reposts', models.IntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VKGroup')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
