# Generated by Django 3.0.8 on 2020-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vkgroup_vkpost_vksource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkgroup',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vkgroup',
            name='site',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
