# Generated by Django 3.0.8 on 2020-08-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_triggernews'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300, null=True)),
                ('members_count', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('site', models.CharField(max_length=200, null=True)),
                ('photo_100', models.URLField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VKSource',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('vk_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='triggernews',
            options={'ordering': ('-last_update',), 'verbose_name': 'Trigger news', 'verbose_name_plural': 'Trigger news'},
        ),
        migrations.CreateModel(
            name='VKPost',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('address', models.SlugField(blank=True, max_length=140, null=True)),
                ('pub_date', models.DateField()),
                ('text', models.CharField(max_length=3000)),
                ('comments', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('reposts', models.PositiveSmallIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VKGroup')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
