# Generated by Django 3.0.8 on 2020-12-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200806_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerphrase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
