# Generated by Django 3.0.8 on 2020-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200718_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkpost',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='vkgroup',
            name='vk_id',
        ),
        migrations.AddField(
            model_name='vkgroup',
            name='id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkpost',
            name='address',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='vkgroup',
            name='members_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vkpost',
            name='comments',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vkpost',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vkpost',
            name='likes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vkpost',
            name='reposts',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
