# Generated by Django 3.0.8 on 2020-12-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_triggerphrase_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggernews',
            name='trigger_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TriggerPhrase'),
        ),
    ]
