# Generated by Django 3.0.8 on 2020-12-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_triggernews_trigger_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggernews',
            name='news_type',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
