# Generated by Django 3.0.8 on 2020-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_triggernews_news_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggernews',
            name='trigger_word',
        ),
        migrations.AddField(
            model_name='triggernews',
            name='trigger_word',
            field=models.ManyToManyField(to='core.TriggerPhrase'),
        ),
    ]
