# Generated by Django 3.1.2 on 2020-12-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201219_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkgroup',
            name='vk_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
