# Generated by Django 3.1.2 on 2020-12-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201223_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='yandexnewstopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
