# Generated by Django 3.0.8 on 2020-12-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201223_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggernews',
            name='tone_type',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=3),
        ),
        migrations.AddField(
            model_name='triggernews',
            name='tone_value',
            field=models.FloatField(default=1.0),
        ),
    ]
