# Generated by Django 3.0.8 on 2021-04-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201225_2047'),
        ('core', '0013_auto_20201226_0014'),
    ]

    operations = [
    ]
