# Generated by Django 3.0.8 on 2021-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20210420_1554'),
        ('core', '0014_merge_20210420_1140'),
    ]

    operations = [
    ]
