# Generated by Django 3.0.8 on 2021-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20210421_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexnewstopic',
            name='name',
            field=models.CharField(db_index=True, max_length=350),
        ),
    ]
