# Generated by Django 3.0.8 on 2021-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210426_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexnewstopic',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
