# Generated by Django 3.0.8 on 2021-04-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210426_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexnewsitem',
            name='link',
            field=models.URLField(max_length=350),
        ),
    ]
