# Generated by Django 3.0.8 on 2021-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210513_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkpost',
            name='address',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
