# Generated by Django 3.0.8 on 2021-05-13 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210513_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triggernews',
            options={'ordering': ('-last_update', '-rate'), 'verbose_name': 'Trigger news', 'verbose_name_plural': 'Trigger news'},
        ),
        migrations.AlterField(
            model_name='triggernews',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
